# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-template
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages, sorting now alphabetically, without the channel prefix!
  - matplotlib=3.0.3        # Current 3.1.0 build incompatible with multiqc=1.7
  - r-base=3.6.1
  - conda-forge::r-data.table=1.12.4
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=1.1

  ## bioconda packages, see above
